<?php
/**
 * Copyright © Magenest JSC. All rights reserved.
 *
 * Created by PhpStorm.
 * User: crist
 * Date: 07/05/2021
 * Time: 10:59
 */

namespace Magenest\Directory\Model\Config\Backend;


class DirectoryFile extends \Magento\Config\Model\Config\Backend\File
{
    protected function _getAllowedExtensions()
    {
        return ['xls', 'xlsx']; // TODO: Change the autogenerated stub
    }
}
