<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var Magento\Customer\Block\Address\Edit $block
 * @var Magento\Framework\Escaper $escaper
 * @var Magenest\Directory\ViewModel\CustomerAddressViewModel $viewModel
 */

$viewModel = $block->getViewModel();
$cityId = $block->getAddress()->getCustomAttribute('city_id') ? $block->getAddress()->getCustomAttribute('city_id')->getValue() : '';
$district = $block->getAddress()->getCustomAttribute('district') ? $block->getAddress()->getCustomAttribute('district')->getValue() : '';
$districtId = $block->getAddress()->getCustomAttribute('district_id') ? $block->getAddress()->getCustomAttribute('district_id')->getValue() : '';
$ward = $block->getAddress()->getCustomAttribute('ward') ? $block->getAddress()->getCustomAttribute('ward')->getValue() : '';
$wardId = $block->getAddress()->getCustomAttribute('ward_id') ? $block->getAddress()->getCustomAttribute('ward_id')->getValue() : '';
?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<form class="form-address-edit"
      action="<?= $escaper->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Contact Information')) ?></span></legend>
        <br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getNameBlockHtml() ?>

        <?php if ($_telephone->isEnabled()): ?>
            <?= $_telephone->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
        <?php endif ?>

        <?php if ($_company->isEnabled()): ?>
            <?= $_company->setCompany($block->getAddress()->getCompany())->toHtml() ?>
        <?php endif ?>

        <?php if ($_fax->isEnabled()): ?>
            <?= $_fax->setFax($block->getAddress()->getFax())->toHtml() ?>
        <?php endif ?>

    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Address')) ?></span></legend>
        <?php $_streetValidationClass = $viewModel->addressGetAttributeValidationClass('street'); ?>

        <?php if ($viewModel->addressIsVatAttributeVisible()): ?>
            <div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?= $escaper->escapeHtml($block->getAttributeData()->getFrontendLabel('vat_id')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('vat_id')) ?>"
                           placeholder="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('vat_id')) ?>"
                           class="input-text <?= $escaper->escapeHtmlAttr($viewModel->addressGetAttributeValidationClass('vat_id')) ?>"
                           id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field city required">
            <label class="label" for="city_id">
                <span><?= $escaper->escapeHtml($block->getAttributeData()->getFrontendLabel('city')) ?></span>
            </label>
            <div class="control">
                <select id="city_id" name="city_id"
                        title="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('city')) ?>"
                        class="validate-select district_id"
                        required>
                </select>
                <input type="text"
                       name="city"
                       style="display: none"
                       value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                       placeholder="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                       class="input-text <?= $escaper->escapeHtmlAttr($viewModel->addressGetAttributeValidationClass('city')) ?>"
                       id="city">
            </div>
        </div>
        <div class="field district required">
            <label class="label" for="district_id">
                <span><?= $escaper->escapeHtml($block->getAttributeData()->getFrontendLabel('district')) ?></span>
            </label>
            <div class="control">
                <select id="district_id" name="district_id"
                        title="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('district')) ?>"
                        class="validate-select district_id"
                        required>
                </select>
                <input type="text"
                       id="district"
                       name="district"
                       style="display: none"
                       value="<?= $escaper->escapeHtmlAttr($district) ?>"
                       title="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('district')) ?>"
                       placeholder="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('district')) ?>"
                       class="input-text">
            </div>
        </div>
        <div class="field ward required">
            <label class="label" for="ward_id">
                <span><?= $escaper->escapeHtml($block->getAttributeData()->getFrontendLabel('ward')) ?></span>
            </label>
            <div class="control">
                <select id="ward_id" name="ward_id"
                        title="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('ward')) ?>"
                        class="validate-select ward_id"
                        required>
                </select>
                <input type="text"
                       id="ward"
                       name="ward"
                       style="display: none"
                       value="<?= $escaper->escapeHtmlAttr($ward) ?>"
                       title="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('ward')) ?>"
                       placeholder="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('ward')) ?>"
                       class="input-text">
            </div>
        </div>
        <div class="field street required">
            <label for="street_1" class="label">
                <span><?= $escaper->escapeHtml($block->getAttributeData()->getFrontendLabel('street')) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('street')) ?>"
                       placeholder="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('street')) ?>"
                       id="street_1"
                       class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>"
                       required>
            </div>
        </div>
        <div class="field zip">
            <label class="label" for="zip">
                <span><?= $escaper->escapeHtml($block->getAttributeData()->getFrontendLabel('postcode')) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                       title="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('postcode')) ?>"
                       placeholder="<?= $escaper->escapeHtmlAttr($block->getAttributeData()->getFrontendLabel('postcode')) ?>"
                       id="zip"
                       class="input-text validate-zip-international <?= $escaper->escapeHtmlAttr($viewModel->addressGetAttributeValidationClass('postcode')) ?>">
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>
        <div class="field country required" style="display: none;">
            <div class="control">
                <input type="hidden" name="country_id" value="VN" title="Country" id="country" class="input-text">
            </div>
        </div>

        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info">
                <span><?= $escaper->escapeHtml(__("It's a default billing address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1"
                       class="checkbox checkbox-custom">
                <label class="label" for="primary_billing">
                    <span><?= $escaper->escapeHtml(__('Use as my default billing address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1"/>
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info">
                <span><?= $escaper->escapeHtml(__("It's a default shipping address.")) ?></span>
            </div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1"class="checkbox checkbox-custom">
                <label class="label" for="primary_shipping">
                    <span><?= $escaper->escapeHtml(__('Use as my default shipping address')) ?></span>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    title="<?= $escaper->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $escaper->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
            }
        },
        ".form-address-edit": {
            "Magenest_Directory/js/field-updater": {
                "form": "#form-validate",
                "defaultCity": "<?= (int)$cityId ?>",
                "defaultDistrict": "<?= (int)$districtId ?>",
                "defaultWard": "<?= (int)$wardId ?>",
                "dataJson": <?= /* @noEscape */ $viewModel->getDataJson() ?>
            }
        }
    }
</script>
