<div class="fullcontent">
    <p>Rich Products Việt Nam là một chi nhánh của tập đoàn Rich Products toàn cầu có trụ sở chính tại Buffalo, New York, Hoa Kỳ, là tập đoàn tiên phong và dẫn đầu trong lĩnh vực công nghiệp thực phẩm đông lạnh không có nguồn gốc từ sữa động vật. Là một doanh nghiệp đứng đầu thị trường, với uy tín trên 20 năm tại thị trường Việt Nam và hơn 70 năm trên thế giới, Rich’s đã và đang làm hài lòng khách hàng với những sản phẩm chất lượng cao và ứng dụng, công thức vượt trội và được đánh giá là một tập đoàn nhạy bén chia sẻ các ý tưởng mới, bí quyết sản xuất và các sản phẩm tiêu chuẩn quốc tế tại Việt Nam và trên toàn thế giới.</p>
    <p>Nhắc đến Rich’s là nhắc đến những giải pháp thực phẩm tối ưu, sự nhiệt tình hỗ trợ khách hàng trong việc phát triển kinh doanh, để lại những ấn tượng khó phai trong lòng khách hàng, và chăm sóc khách hàng như chính người thân trong gia đình.</p>
    <p>Phân phối sản phẩm trên toàn quốc và có văn phòng đại diện tại Tp. Hồ Chí Minh, Hà Nội, Đà Nẵng và Cần Thơ, Rich’s vẫn đang không ngừng mở rộng mạng lưới văn phòng đại diện của mình. Ngoài ra, sản phẩm của công ty còn được xuất khẩu sang các nước lân cận và nhận được nhiều chứng nhận về chất lượng như ISO, HACCP và HALAL.</p>
    <p>Sản phẩm của Rich’s được nhiều người biết đến nhất là Gold Label (hay còn gọi là kem nhãn vàng) đã trở thành sự lựa chọn hàng đầu của các chuyên gia làm bánh kem do có độ nở cao, màu trắng tinh khiết dễ pha trộn và hương vị sữa độc đáo có nguồn gốc từ thực vật.</p>
    <p>Ngoài ra, Rich’s đã phát triển rất nhiều sản phẩm khác có tính năng vượt trội, phá vỡ các giới hạn và quan niệm cũ về ngành thực phẩm. Một trong những ứng dụng vượt trội này là bột trộn bánh choux và bột trộn custard, giúp giảm thiểu tối đa thời gian làm ra một mẻ bánh bằng cách bỏ qua công đoạn nấu nhân truyền thống.</p>
    <p>Không chỉ giới hạn phạm vi ứng dụng trong lĩnh vực bánh kem, các sản phẩm của Rich’s còn được sử dụng trong nhiều công thức nấu ăn cũng như pha chế đồ uống. Chúng tôi đã phát triển được những công thức gây sốt trên thị trường như trà foam sữa hay kem trang trí đồ uống bằng sô-cô-la.</p>
    <p>Với mục tiêu vì sự phát triển của khách hàng và mong đợi nền công nghiệp thực phẩm Việt Nam vươn lên tầm cao mới, Rich’s luôn không ngừng sáng tạo ra những ý tưởng, công thức và sản phẩm chất lượng cao, đem lại sự hài lòng tuyệt đối cho khách hàng.</p>
    Hãy liên hệ với chúng tôi để được tư vấn thêm:
    <ul>
        <li><strong>Tel:</strong>
            <span>+84 28 3866 4888</span>
        </li>
        <li><strong>Fax:</strong>
            <span>+84 28 3866 2679</span>
        </li>
        <li><strong>Email:</strong>
            <span>ChamSocKhachHang@rich.com</span>
        </li>
    </ul>
</div>
