<div class="b2me-block">
    <div class="b2me-block-text">
        <h1 class="b2me-block-title">
            {{trans "Cổng thông tin B2ME"}}
        </h1>
        <p>{{trans "Nơi chúng tôi có thể giúp bạn biến ước mơ thành hiện thực:"}}</p>
        <ul class="b2me-block-list">
            <li class="b2me-block-item">{{trans "Sản phẩm sáng tạo"}}</li>
            <li class="b2me-block-item">{{trans "Tư vấn trực tiếp"}}</li>
            <li class="b2me-block-item">{{trans "Giảm giá đặc biệt"}}</li>
            <li class="b2me-block-item">{{trans "Demo riêng tư"}}</li>
            <li class="b2me-block-item">{{trans "Chiến dịch quảng cáo"}}</li>
        </ul>
        <p>{{trans "Tất cả những gì bạn cần làm là ..."}}</p>
        <a class="b2me-block-link" href="#">{{trans "Hãy cùng làm quen nào"}}</a>
    </div>
    <img src="" alt="">
</div>

