<div class="footer_links_box">
    <div class="footer-column footer-column-1">
        <div><strong class="footer-title">{{trans "CÔNG TY TNHH RICH PRODUCTS VIỆT NAM"}}</strong></div>
        <div>{{trans "Số Giấy chứng nhận đăng ký doanh nghiệp số: 3700763669 do: Sở kế hoạch đầu tư tỉnh Bình Dương cấp ngày: 19/10/2006"}}</div>
        <div><strong class="footer-column-title">{{trans "Địa chỉ trụ sở:"}}</strong><span class="footer-column-content">{{trans "Số 27 VSIP II đường số 3, khu công nghiệp Việt Nam-Singapore II, Khu liên hợp công nghiệp - dịch vụ - đô thị Bình Dương, Phường Hoà Phú, Thành phố Thủ Dầu Một, Tỉnh Bình Dương, Việt Nam"}}</span></div>
        <div><strong class="footer-column-title">{{trans "Địa chỉ văn phòng:"}}</strong><span class="footer-column-content">{{trans "Tầng 15, Tòa nhà Xổ Số Kiến Thiết, 77 Trần Nhân Tôn, Phường 9, Quận 5, Tp. Hồ Chí Minh"}}</span></div>
        <div><strong class="footer-column-title">Hotline</strong><span class="footer-column-content">(028) 3866 4789</span></div>
        <div><strong class="footer-column-title">Email</strong> <a class="footer-column-content" href="mailto:ecommercevn@rich.com">ecommercevn@rich.com</a></div>
        <div class="connect-socials"><strong class="footer-column-title title-not-js">{{trans "Kết nối với Rich's"}}</strong> <a class="fb-icon" href="https://www.facebook.com/RichProductsVietnam"><span style="display: none;">Facebook</span></a> <a class="ig-icon" href="https://www.instagram.com/richproductsvietnam/"><span style="display: none;">Instagram</span></a> <a class="yt-icon" href="#"><span style="display: none;">Youtube</span></a></div>
        <img class="img-bct-mobile" src="{{media url="wysiwyg/logoSaleNoti.png"}}" alt="" />
</div>
    <div class="footer-column footer-js footer-column-2">
        <div class="footer-column-child"><strong class="footer-column-title">{{trans "Về Rich's"}}</strong>
            <ul class="footer-column-content">
                <li><a href="{{store url=''}}about-us">{{trans "Giới thiệu về chúng tôi"}}</a></li>
                <li><a href="{{store url=''}}terms-conditions">{{trans "Điều khoản và điều kiện"}}</a></li>
                <li><a href="{{store url=''}}shopping-payment-direction">{{trans "Hướng dẫn mua hàng và thanh toán"}}</a></li>
                <li><a href="{{store url=''}}contact">{{trans "Liên hệ chúng tôi"}}</a></li>
            </ul>
        </div>
        <div class="footer-column-child"><strong class="footer-column-title title-not-js">{{trans "Hợp tác với RICH'S"}}</strong>
            <ul class="footer-column-content">
                <li><a href="{{store url=''}}b2me">{{trans "B2Me - Business Hub for F&amp;B Business"}}</a></li>
            </ul>
        </div>
        <div class="footer-column-child payment-methods"><strong class="footer-column-title title-not-js">{{trans "Phương thức thanh toán"}}</strong>
            <div class="footer-column-content"><img src="{{media url="wysiwyg/VISA.png"}}" alt="" /> <img src="{{media url="wysiwyg/AMERICAGROUP.png"}}" alt="" /> <img src="{{media url="wysiwyg/MASTERCARD.png"}}" alt="" /> <img src="{{media url="wysiwyg/PAYPAL.png"}}" alt="" /></div>
        </div>
        <div class="connect-socials"><strong class="footer-column-title title-not-js">{{trans "Kết nối với Richs"}}</strong> <a class="fb-icon" href="https://www.facebook.com/RichProductsVietnam"><span style="display: none;">Facebook</span></a> <a class="ig-icon" href="https://www.instagram.com/richproductsvietnam/"><span style="display: none;">Instagram</span></a> <a class="yt-icon" href="#"><span style="display: none;">Youtube</span></a></div>
        <div class="richs-download"><strong class="footer-column-title title-not-js">{{trans "Download the RICH'S app"}}</strong>
            <div class="download-img"><img src="{{media url="wysiwyg/Group_750.png"}}" alt="" />
                <div class="richs-download-app"><a href="https://play.google.com/store/apps/details?id=com.richproducts.customerapp"><img src="{{media url="wysiwyg/google-play-android.png"}}" alt="" /> </a> <a href="https://apps.apple.com/vn/app/rich-products-vietnam/id1513567328"><img src="{{media url="wysiwyg/app-store.png"}}" alt="" /></a></div>
            </div>
        </div>
    </div>
    <div class="footer-column footer-js footer-column-3"><strong class="footer-column-title">{{trans "Sản phẩm"}}</strong>
        <ul class="footer-column-content">
            <li><a href="{{store url=''}}bakery-product.html">{{trans "Kem làm bánh"}}</a></li>
            <li><a href="{{store url=''}}bakery-mixes.html">{{trans "Bột trộn"}}</a></li>
            <li><a href="{{store url=''}}beverages-bases.html">{{trans "Kem pha chế"}}</a></li>
            <li><a href="{{store url=''}}syrup-sauce.html">{{trans "Siro &amp; Sốt"}}</a></li>
            <li><a href="{{store url=''}}fruit-filling.html">{{trans "Mứt trái cây"}}</a></li>
            <li><a href="{{store url=''}}pudding-chocolate.html">{{trans "Pudding &amp; Socola"}}</a></li>
            <li><a href="{{store url=''}}cooking-ingredients.html">{{trans "Nguyên liệu nấu bánh"}}</a></li>
            <li><a href="{{store url=''}}ready-to-use.html">{{trans "Bánh lạnh"}}</a></li>
        </ul>
    </div>
    <div class="footer-column footer-js footer-column-4"><strong class="footer-column-title">{{trans "Công thức"}}</strong>
        <ul class="footer-column-content">
            <li><a href="{{store url=''}}article/recipes/browselist/cid/1/">{{trans "Bếp bánh"}}</a></li>
            <li><a href="{{store url=''}}article/recipes/browselist/cid/4/">{{trans "Pha chế"}}</a></li>
            <li><a href="{{store url=''}}article/recipes/browselist/cid/2/">{{trans "Tráng miệng"}}</a></li>
            <li><a href="{{store url=''}}article/recipes/browselist/cid/3/">{{trans "Nấu ăn"}}</a></li>
        </ul>
        <img class="img-bct-desktop" src="{{media url="wysiwyg/logoSaleNoti.png"}}" alt="" />
    </div>
    <div class="footer-column footer-js footer-column-mobile">
        <div class="footer-column-child"><strong class="footer-column-title">{{trans "Về Rich's"}}</strong>
            <ul class="footer-column-content">
                <li><a href="{{store url=''}}about-us">{{trans "Giới thiệu về chúng tôi"}}</a></li>
                <li><a href="{{store url=''}}terms-conditions">{{trans "Điều khoản và điều kiện"}}</a></li>
                <li><a href="{{store url=''}}shopping-payment-direction">{{trans "Hướng dẫn mua hàng và thanh toán"}}</a></li>
                <li><a href="{{store url=''}}contact">{{trans "Liên hệ chúng tôi"}}</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="footer-bottom">@ Copyright 2021 RICH'S. All rights reserved.</div>
