<div class="category-list">
    <div id="home-category" class="owl-carousel owl-theme">
        <div class="category-item"><a href="{{store url=topping-cream.html}}"><img src="{{media url="wysiwyg/NoPath_-_Copy_18_.png"}}" alt="" />{{trans "Kem làm bánh"}}</a></div>
        <div class="category-item"><a href="{{store url=bakery-mixes.html}}"><img src="{{media url="wysiwyg/NoPath_-_Copy_19_.png"}}" alt="" />{{trans "Bột trộn"}}</a></div>
        <div class="category-item"><a href="{{store url=beverages-bases.html}}"><img src="{{media url="wysiwyg/NoPath_-_Copy_20_.png"}}" alt="" />{{trans "Kem pha chế"}}</a></div>
        <div class="category-item"><a href="{{store url=syrup-sauce.html}}"><img src="{{media url="wysiwyg/NoPath_-_Copy_21_.png"}}" alt="" />{{trans "Siro &amp; Sốt"}}</a></div>
        <div class="category-item"><a href="{{store url=fruit-filling.html}}"><img src="{{media url="wysiwyg/NoPath_-_Copy_22_.png"}}" alt="" />{{trans "Mứt trái cây"}}</a></div>
        <div class="category-item"><a href="{{store url=pudding-chocolate.html}}"><img src="{{media url="wysiwyg/NoPath_-_Copy_23_.png"}}" alt="" />{{trans "Pudding &amp; Socola"}}</a></div>
        <div class="category-item"><a href="{{store url=cooking-ingredients.html}}"><img src="{{media url="wysiwyg/NoPath_-_Copy_24_.png"}}" alt="" />{{trans "Nguyên liệu nấu ăn"}}</a></div>
        <div class="category-item"><a href="{{store url=ready-to-use.html}}"><img src="{{media url="wysiwyg/NoPath_-_Copy_25_.png"}}" alt="" />{{trans "Bánh lạnh"}}</a></div>
    </div>
</div>
<div>{{block class="Magento\Framework\View\Element\Template" name="home.category" template="Magento_Cms::homeCategory.phtml"}}</div>
