<div>{{block class="Mageplaza\Productslider\Block\CategoryId" template="Mageplaza_Productslider::productslider.phtml" products_count="20" category_id="3"}}</div>
<div>{{block class="Mageplaza\Productslider\Block\CategoryId" template="Mageplaza_Productslider::productslider.phtml" products_count="20" category_id="50"}}</div>
<div>{{block class="Maijindou\Sales\Block\BestSellerProducts" template="Mageplaza_Productslider::productslider1.phtml" products_count="20" category_id="51"}}</div>
<div>{{block class="Maijindou\Sales\Block\BestSellerProducts" template="Mageplaza_Productslider::productslider1.phtml" products_count="20" category_id="52"}}</div>
