<div>{{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="39"}}</div>
<div>{{widget type="Magenest\CatalogProduct\Block\Homepage\Category\ProductWidget" block_title="Rich's Deal" product_count_limit="20" exclude_ending_soon="1" id_path="category/84"}}</div>
<div>{{widget type="Magento\Cms\Block\Widget\Block" template="widget/static_block/default.phtml" block_id="51"}}</div>
<div>{{widget type="Magefan\Blog\Block\Widget\Recent" title="Công thức xu hướng" number_of_posts="20" category_id="1" tag_id="0" author_id="0" custom_template="Magefan_Blog::newPosts.phtml"}}</div>
<div>{{widget type="Magenest\CouponCode\Block\Widget\CouponList"}}</div>
