<div class="cms-membership-banner">
    <img src="{{view url='Magenest_Core::images/membership/banner.png'}}" alt="membership"/>
</div>
<div class="cms-membership-title">
    <img src="{{view url='Magenest_Core::images/membership/gift-icon.svg'}}" alt="gift"/>
    <h1>Chính sách quản lý điểm</h1>
</div>
<div class="cms-membership-content">
    <ol class="cms-membership-policy">
        <li>
            <strong>Thu thập Rich's Point:</strong>
            <div style="font-size: 16px;">Khách hàng thành viên có thể thu thập được Rich's point khi mua sắm trên nền tảng Rich's Mall với tỉ lệ quy đổi: 50.000 VND = 1 point.</div>
        </li>
        <li>
            <strong>Hạng thành viên và quyền lợi:</strong>
            <div>
                <div class="membership-class-table">
                    <table>
                    <thead>
                    <tr>
                        <th colspan="3"></th>
                        <th colspan="3">Quyền lợi khách hàng</th>
                    </tr>
                    <tr>
                        <th>Quy đổi Rich's Point</th>
                        <th>Hạng thành viên</th>
                        <th>Điểm tích lũy</th>
                        <th><strong>Recipe</strong></th>
                        <th><strong>Video</strong></th>
                        <th><strong>Menu Collection</strong></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td rowspan="5">
                            <ul>
                                <li>1 Point = 100 VND</li>
                                <li>4 Points = 1 Recipe</li>
                                <li>10 Points = 1 Video</li>
                                <li>80 Points = 1 Menu collection</li>
                            </ul>
                        </td>
                        <td>Bronze</td>
                        <td>0-50</td>
                        <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="16"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/close-icon.svg'}}" alt="" width="11"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/close-icon.svg'}}" alt="" width="11"/></td>
                    </tr>
                    <tr>
                        <td>Silver</td>
                        <td>51-150</td>
                        <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="16"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="16"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/close-icon.svg'}}" alt="" width="11"/></td>
                    </tr>
                    <tr>
                        <td>Gold</td>
                        <td>151-300</td>
                        <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="16"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="16"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="16"/></td>
                    </tr>
                    <tr>
                        <td>Platinum</td>
                        <td>301-600</td>
                        <td><img src="{{view url='Magenest_Core::images/membership/unlimited-icon.svg'}}" alt="" width="24"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="16"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="16"/></td>
                    </tr>
                    <tr>
                        <td>Diamond</td>
                        <td>601+</td>
                        <td><img src="{{view url='Magenest_Core::images/membership/unlimited-icon.svg'}}" alt="" width="24"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/unlimited-icon.svg'}}" alt="" width="24"/></td>
                        <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="16"/></td>
                    </tr>
                    </tbody>
                </table>
                </div>
                <div class="membership-class-content">
                    <p><strong>Chú thích:</strong></p>
                    <table class="membership-class-annotate">
                        <tbody>
                        <tr>
                            <td><img src="{{view url='Magenest_Core::images/membership/check-icon.svg'}}" alt="" width="13"/></td>
                            <td>Có thể dùng điểm redeem</td>
                        </tr>
                        <tr>
                            <td><img src="{{view url='Magenest_Core::images/membership/close-icon.svg'}}" alt="" width="11"/></td>
                            <td>Chưa thể dùng điểm redeem</td>
                        </tr>
                        <tr>
                            <td><img src="{{view url='Magenest_Core::images/membership/unlimited-icon.svg'}}" alt="" width="19"/></td>
                            <td>Xem không giới hạn (tất cả các nội dung khóa đều được xem không tốn điểm)</td>
                        </tr>
                        </tbody>
                    </table>
                    <p><strong>Quyền lợi thành viên:</strong></p>
                    <div class="benefits-item"><span class="benefits-title">Recipe, Video, Menu Collection:</span> Lưu trữ dưới dạng thông tin số, khách hàng redeem điểm để xem nội dung. Không hỗ trợ tải về.</div>
                    <div class="benefits-item training-classes">
                        <span class="benefits-title">Training classes:</span>
                        <ul>
                            <li>Tổ chức tập trung với kết hợp giữa online và offline.</li>
                            <li>Khi có lịch tổ chức, admin sẽ upload trực tiếp lên Website và gửi mail đến khách hàng để "buy ticket" bằng cách redeem điểm.</li>
                            <li>Khi không có lịch, phần này sẽ bị ẩn đi.</li>
                        </ul>
                    </div>
                    <div class="benefits-item"><span class="benefits-title">Private demo:</span> Khách hàng redeem điểm để yêu cầu NV kỹ thuật Rich's demo riêng theo yêu cầu với hình thức online.</div>
                </div>
            </div>
        </li>
        <li>
            <strong>Biến động số dư điểm và thay đổi hạng thành viên:</strong>
            <div style="padding-left: 17px;">
                <p>- Rich's point sẽ hết hạn trong <b>180 ngày</b> kể từ lần mua hàng cuối cùng. (Pop-up thông báo vào Notification trước 7 ngày). Số điểm mất đi sẽ không ảnh hưởng tới xếp hạng thành viên.</p>
                <p>- Xếp hạng thành viên sẽ trở về "Bronze" sau <b>365 ngày</b> không phát sinh đơn hàng (Pop-up thông báo vào Notification trước 7 ngày).</p>
            </div>
        </li>
    </ol>
</div>
