<div class="app-banner"><img class="app-banner-desktop" src="{{media url="wysiwyg/NoPath.png"}}" alt="" />
    <div class="app-banner-text">
        <p class="app-banner-sub">Rich's - Thích là Click</p>
        <h3 class="app-banner-title">Mua hàng dễ dàng với ứng dụng Rich's Product</h3>
        <div class="app-banner-download"><img src="{{media url="wysiwyg/Group_750.png"}}" alt="" />
            <div class="download-img">
                <a href="https://play.google.com/store/apps/details?id=com.richproducts.customerapp"><img src="{{media url="wysiwyg/google-play-android.png"}}" alt="" /> </a>
                <a href="https://apps.apple.com/vn/app/rich-products-vietnam/id1513567328"><img src="{{media url="wysiwyg/app-store.png"}}" alt="" /></div></a>
        </div>
    </div>
    <img class="app-banner-mobile" src="{{media url="wysiwyg/NoPath_2x.png"}}" alt="" /></div>
