<div class="app-benefit">
    <h3 class="app-benefit-title">Ứng dụng Rich's đem tới những gì?</h3>
    <div class="app-benefit-list">
        <div class="app-benefit-item"><img src="{{media url="wysiwyg/Apps_introduce-03.png"}}" alt=""> <strong>Dễ dàng mua sắm</strong>
            <p>Với hàng trăm sản phẩm để lựa chọn, bạn có thể nhận được chính xác những gì bạn cần sau vài giây, ngay từ điện thoại của mình.</p>
        </div>
        <div class="app-benefit-item"><img src="{{media url="wysiwyg/NoPath_-_Copy.png"}}" alt=""> <strong>Ưu đãi khách hàng</strong>
            <p>Tận hưởng các lợi ích độc quyền khi mua sắm với Rich's, từ kiếm xu của Rich's đến tiết kiệm tiền với các giao dịch mua sắm trong tầm tay bạn</p>
        </div>
        <div class="app-benefit-item"><img src="{{media url="wysiwyg/NoPath_-_Copy_2_.png"}}" alt=""> <strong>Khám phá công thức độc quyền</strong>
            <p>Khám phá công thức và video mới nhất của chúng tôi, độc quyền trên Ứng dụng Rich Products</p>
        </div>
    </div>
</div>
