<div>
    {{block class="Magento\\Cms\\Block\\Block" block_id="app.banner"}}
</div>
<div>
    {{block class="Magento\\Cms\\Block\\Block" block_id="app.benefit"}}
</div>
<div>
    {{block class="Magento\\Cms\\Block\\Block" block_id="app.reason"}}
</div>
<div>
    {{block class="Magento\\Cms\\Block\\Block" block_id="app.video"}}
</div>
<div>
    {{block class="Magento\\Cms\\Block\\Block" block_id="app.banner.last"}}
</div>
