<div class="app-video">
    <div class="app-video-container">
        {{block class="Magento\Framework\View\Element\Template" name="app.video" template="Magento_Cms::app-mobile-video.phtml"}}

        <div class="app-reason">
            <h3 class="app-reason-title">Tại sao lại chọn Rich's Product</h3>
            <p class="app-reason-sub">Nâng cao trải nghiệm mua sắm của bạn</p>
            <p class="app-reason-des">Sử dụng tính năng trò chuyện của ứng dụng để dễ dàng kết nối với Dịch vụ khách hàng. Hãy để Rich's tạo nguồn cảm hứng cho những món bánh của bạn.</p>
        </div>
    </div>
</div>

