<div class="app-banner-last"><img class="app-banner-last-desktop" src="{{media url="wysiwyg/app-banner-last.png"}}" alt="" /> <img class="app-banner-last-mobile" src="{{media url="wysiwyg/app-banner-last-mobile.png"}}" alt="" />
    <div class="app-banner-last-text">
        <div class="app-banner-last-list">
            <div class="app-banner-last-item"><img src="{{media url="wysiwyg/step1-img.png"}}" alt="" />
                <div class="app-banner-last-step"><strong class="title">{{trans "Easy registration"}}</strong> <strong class="step">{{trans "Step 1"}}</strong>
                    <p>{{trans 'Get the app. Enter your phone number and press the "Get code" button'}}</p>
                    <img src="{{media url="wysiwyg/QR-code-1.png"}}" alt="" /> <img src="{{media url="wysiwyg/QR-code-2.png"}}" alt="" /> <a href="https://apps.apple.com/vn/app/rich-products-vietnam/id1513567328"><img src="{{media url="wysiwyg/gg-play-download_1.png"}}" alt="" /> </a> <a href="https://play.google.com/store/apps/details?id=com.richproducts.customerapp"><img src="{{media url="wysiwyg/app-store-download.png"}}" alt="" /></a></div>
            </div>
            <div class="app-banner-last-item"><img src="{{media url="wysiwyg/step2-img.png"}}" alt="" />
                <div class="app-banner-last-step"><strong class="step">{{trans "Step 2"}}</strong>
                    <p>{{trans "Confirm the OTP sent to your phone"}}</p>
                </div>
            </div>
            <div class="app-banner-last-item"><img src="{{media url="wysiwyg/step3-img.png"}}" alt="" />
                <div class="app-banner-last-step"><strong class="step">{{trans "Step 3"}}</strong>
                    <p>{{trans "Enjoy your shopping and get customer reward"}}</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div>{{block class="Magento\Framework\View\Element\Template" template="Magento_Cms::cms-app-step-slider.phtml"}}</div>
