<div class="shipping-method">
    <div class="shipping-method-item">
        <img src="{{media url="wysiwyg/delivery-truck.png"}}" alt="">
        <div class="shipping-method-text">
            <strong class="shipping-method-title">{{trans "Free shipping" }}</strong>
            <span class="shipping-method-des">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
        </div>
    </div>
    <div class="shipping-method-item">
        <img src="{{media url="wysiwyg/online-shop_1_.png"}}" alt="">
        <div class="shipping-method-text">
            <strong class="shipping-method-title">{{trans "Return conditions" }}</strong>
            <span class="shipping-method-des">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
        </div>
    </div>
    <div class="shipping-method-item">
        <img src="{{media url="wysiwyg/deal.png"}}" alt="">
        <div class="shipping-method-text">
            <strong class="shipping-method-title">{{trans "Rewards program" }}</strong>
            <span class="shipping-method-des">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
        </div>
    </div>
</div>
