<div class="mgn_shop-pay-direction">
    <h1>Hướng dẫn đặt hàng và thanh toán</h1>
    <strong>1. Quy trình đặt hàng</strong><br>
    <br>
    Bước 1: Quý khách hàng tiến hành đăng nhập vào Website để mua sắm. <br>
    <br>
    Bước 2: Quý khách hàng lựa chọn hàng hóa được trưng bày trên website với số lượng và loại hàng hóa mong muốn.<br>
    <br>
    Bước 3: Quý khách hàng nhấp chọn “Mua ngay” hoặc “Thêm vào giỏ hàng” để tiếp tục thực hiện việc mua sắm. <br>
    <br>
    Bước 4: Tại giỏ hàng Quý khách hàng chỉnh sửa/ cập nhật đơn hàng. Sau đó nhấp chọn “Tiến hành thanh toán”. <br>
    <br>
    Bước 5: Quý khách hàng điền đầy đủ thông tin theo yêu cầu. <br>
    <br>
    Bước 6: Quý khách hàng rà soát lại đơn hàng và nhấp chọn “Đặt hàng”. <br>
    <br>
    Bước 7: Richs sẽ gửi email xác nhận đơn hàng tới email Quý khách hàng dùng để đăng ký tài khoản trên shop.richs.com.vn. <br>
    <br>
    Bước 8. Các bên thực hiện giao hàng và thanh toán. <br>
    <br>
    <br>
    <strong>2. Phương thức thanh toán</strong><br>
    <br>
    Richs chỉ cung cấp hình thức thanh toán trực tiếp khi giao hàng cho Quý khách hàng. <br>
    <br>
    Richs luôn hoan nghênh mọi ý kiến đóng góp thiện chí của Quý khách hàng để hoàn thiện hơn nữa chất lượng sản phẩm và dịch vụ của mình.
</div>
