<div class="policy-navigation">
    <div class="title">Điều khoản & dịch vụ</div>
    <ul>
        <li class="policy-item"><a href="{{store url=''}}terms-conditions">Điều khoản sử dụng chung</a></li>
        <li class="policy-item"><a href="#">Giải quyết khiếu nại</a></li>
        <li class="policy-item"><a href="#">Chính sách đổi trả</a></li>
        <li class="policy-item"><a href="#">Chính sách giao hàng</a></li>
        <li class="policy-item"><a href="#">Thanh toán và yêu cầu hóa đơn</a></li>
        <li class="policy-item"><a href="#">Chấm dứt hoạt động của tài khoản thành viên</a></li>
        <li class="policy-item"><a href="#">Chính sách bảo vệ thông tin cá nhân</a></li>
    </ul>
</div>
