<div class="full-content">
    <strong>1.1. Giới thiệu về Rich Products Việt Nam:</strong><br>
    <br>
    a. Chào mừng Quý khách hàng đến với Rich Products Việt Nam (sau đây sẽ được gọi tắt là “Richs” hoặc “Chúng tôi”).<br>
    <br>
    b. Rich Products Việt Nam có địa chỉ trụ sở tại Số 27 VSIP II đường số 3, khu công nghiệp Việt Nam-Singapore II, Khu liên hợp công nghiệp - dịch vụ - đô thị Bình Dương, Phường Hoà Phú, Thành phố Thủ Dầu Một, Tỉnh Bình Dương, Việt Nam thành lập website hỗ trợ giao dịch trực tuyến tại www.shop.richs.com.vn (sau đây gọi tắt là “Website”).<br>
    <br>
    c. Khi Quý khách hàng truy cập hoặc sử dụng dịch vụ của Chúng tôi trên Website có nghĩa là Quý khách hàng đã đồng ý với các điều khoản này, vào bất cứ lúc nào. Các thay đổi về chính sách, điều khoản có hiệu lực ngay khi được đăng tải trên Website. Chúng tôi sẽ thông báo qua Email cho Quý khách hàng khi có sự thay đổi về Chính sách, điều khoản. Khi tiếp tục sử dụng dịch vụ của Chúng tôi, có nghĩa là Quý khách hàng đã đồng ý với các thay đổi cập nhật trong điều khoản, chính sách.<br>
    <br>
    d. Quý khách hàng vui lòng kiểm tra thường xuyên để cập nhật những thay đổi từ phía Chúng tôi.<br>
    <br>
    <strong>1.2. Quy định sử dụng Website:</strong><br>
    <br>
    a. Khi truy cập vào Website của Chúng tôi, Quý khách hàng phải đảm bảo có đầy đủ năng lực hành vi dân sự để thực hiện các giao dịch theo quy định hiện hành của Pháp luật Việt Nam. Quý khách hàng chưa đủ 18 tuổi phải truy cập, giao dịch dưới sự giám sát của cha mẹ hoặc người giám hộ hợp pháp.<br>
    <br>
    b. Theo yêu cầu đăng ký từ Quý khách hàng, Chúng tôi sẽ cấp 1 Tài khoản thành viên để Quý khách hàng có thể thực hiện mua sắm, giao dịch trên Website theo khuôn khổ của Điều khoản sử dụng đã đề ra.<br>
    <br>
    c. Thông qua việc đăng ký Tài khoản thành viên, Quý khách hàng sẽ phải cung cấp thông tin xác thực về bản thân và thường xuyên cập nhật nếu có thay đổi để không ảnh hưởng đến tính chính xác của giao dịch. Chúng tôi sẽ dựa trên các thông tin mà Quý khách hàng đã cung cấp tại Tài khoản thành viên để cung ứng Hàng hóa, Dịch vụ tới Quý khách hàng. Mỗi Quý khách hàng phải có trách nhiệm với Tài khoản thành viên, mật khẩu và tất cả hoạt động giao dịch của mình trên Website. Khi phát hiện tài khoản bị truy cập trái phép. Chúng tôi không chịu bất cứ trách nhiệm nào dù trực tiếp hay gián tiếp đối với những thiệt hại, mất mát do Quý khách hàng không tuân thủ quy định hoặc không đảm bảo yếu tố bảo mật.<br>
    <br>
    d. Nghiêm cấm sử dụng bất kỳ chức năng nào của Website vào mục đích thương mại khác hoặc làm phương hại đến lợi ích của bất kỳ bên nào, hoặc dùng để vi phạm pháp luật. Hành vi vi phạm tùy theo mức độ sẽ chịu sự chế tài của quy định pháp luật hiện hành. Chúng tôi có quyền tự mình hủy Tài khoản thành viên có hành vi vi phạm hoặc theo yêu cầu của cơ quan Nhà nước.<br>
    <br>
    e.Trong suốt quá trình sử dụng, Quý khách hàng đồng ý nhận email, thông báo quảng cáo từ Website của Richs. Nếu không muốn tiếp tục nhận các thông tin này, quý khách có thể nhấp vào liên kết ở cuối email hoặc gửi email đến ecommercevn@rich.com để được hỗ trợ.<br>
    <br>
    <strong>1.3. Ý kiến Quý khách hàng:</strong><br>
    <br>
    Tất cả đánh giá, xếp hạng của Quý khách hàng là tài sản của Chúng tôi. Những ý kiến, đánh giá này nhằm mục đích cải thiện chất lượng dịch vụ của Richs. Các trường hợp đăng tải đánh giá với thông tin giả mạo, vu khống, tuyên truyền nội dung không phù hợp với quy định hiện hành của Pháp luật Việt Nam thì chủ Tài khoản thành viên phải tự chịu trách nhiệm trước Pháp luật Việt Nam. Chúng tôi có quyền xóa đánh giá và hủy kích hoạt Tài khoản thành viên vi phạm trên.<br>
    <br>
    <strong>1.4. Chấp nhận đơn hàng và giá cả:</strong><br>
    <br>
    a. Chúng tôi có quyền từ chối hoặc hủy đơn hàng vì các lý do kỹ thuật, lợi dụng lỗ hổng bảo mật hay bất cứ hành vi nào từ Quý khách hàng đi ngược lại quy định hiện hành của Pháp luật Việt Nam.<br>
    <br>
    b. Chúng tôi cam kết cung cấp giá cả chính xác cho Quý khách hàng. Bằng việc đặt hàng trực tuyến, Quý khách hàng đã đồng ý với chính sách giá niêm yết của Richs trên từng sản phẩm.<br>
    <br>
    <strong>1.5. Thay đổi hoặc hủy bỏ đơn hàng:</strong><br>
    <br>
    a. Quý khách hàng có thể hủy bỏ đơn hàng theo cách:<br>
    <br>
    Hủy đơn hàng trên Website thông qua Tài khoản thành viên<br>
    Gọi điện thoại trực tiếp về số: <a href="tel: 02838664789" class="text-inherit">(028) 3866 4789</a><br>
    Gửi email tại: <a href="mailto: ecommercevn@rich.com" class="text-inherit">ecommercevn@rich.com</a><br>
    <br>
    b. Tình trạng đơn hàng sẽ được thông báo đến Quý khách hàng qua Website của Richs. Quy trình xử lý đơn hàng của Richs bao gồm:<br>
    <br>
    <table class="order-status-tabel">
        <thead>
        <tr>
            <th>Tình trạng đơn hàng</th>
            <th>Diễn giải</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Đã tiếp cận</td>
            <td>Website đã ghi nhận yêu cầu mua hàng</td>
        </tr>
        <tr>
            <td>Đã xác nhận</td>
            <td>Đơn hàng đã đóng gói và giao cho đơn vị vận chuyển</td>
        </tr>
        <tr>
            <td>Đang giao hàng</td>
            <td>Đơn vị vận chuyển đang mang kiện hàng đến với Quý khách hàng</td>
        </tr>
        <tr>
            <td>Đã giao hàng chờ xác nhận</td>
            <td>Đơn vị vận chuyển xác nhận đã giao hàng. Chờ Quý khách hàng đánh giá và xác nhận trên Website</td>
        </tr>
        <tr>
            <td>Hoàn thành</td>
            <td>Đã được Quý khách hàng đánh giá xác nhận trên Website Richs hoặc đã hết thời gian đổi trả</td>
        </tr>
        </tbody>
    </table>
    <br>
    c. Đơn hàng “Đã xác nhận” đồng nghĩa với việc đơn hàng đã được đóng gói và giao cho đơn vị vận chuyển. Chúng tôi không hỗ trợ hủy đơn hàng trong trường hợp đơn hàng đã được xử lý tới giai đoạn này.<br>
    <br>
    d. Tùy vào tính chất và mức độ, Richs có quyền từ chối phục vụ và/hoặc khóa Tài khoản thành viên không cần báo trước hoặc chuyển thông tin cho cơ quan chức năng xử lý theo quy định hiện hành của Pháp luật Việt Nam với những trường hợp lợi dụng chính sách hủy đơn hàng nhằm mục đích phá hoại, cạnh tranh không lành mạnh.<br>
    <br>
    <strong>1.6. Thương hiệu và bản quyền:</strong><br>
    <br>
    Mọi quyền sở hữu trí tuệ, nội dung thông tin và tất cả các thiết kế, văn bản, đồ họa, phần mềm, hình ảnh, video, âm thanh, mã nguồn đều thuộc tài sản của Richs. Chúng tôi không chịu trách nhiệm về các hành vi sử dụng các tài sản trên vào mục đích khác mà chưa được sự đồng ý chính thức của đại diện hợp pháp từ phía Richs.<br>
    <br>
    <strong>1.7. Quyền pháp lý:</strong><br>
    <br>
    Các điều kiện, điều khoản, nội dung trên Website của Richs được điều chỉnh bởi Pháp luật Việt Nam và Tòa án có thẩm quyền tại Việt Nam sẽ giải quyết bất kỳ tranh chấp nào phát sinh.<br>
    <br>
    <strong>1.8. Quy định về bảo mật:</strong><br>
    <br>
    a. Website của Chúng tôi coi trọng việc bảo mật và áp dụng các biện pháp tốt nhất để bảo vệ thông tin cá nhân của Quý khách hàng.<br>
    <br>
    b. Nội dung chi tiết, vui lòng xem thêm tại Chính sách bảo vệ thông tin cá nhân bên dưới.<br>
    <br>
    c. Quý khách hàng không được dùng bất kỳ công cụ hay hình thức can thiệp nào để thay đổi cấu trúc dữ liệu, hệ thống và giao diện của Website. <br>
    <br>
    <strong>1.9. Giao dịch an toàn:</strong><br>
    <br>
    Richs chỉ cung cấp hình thức thanh toán trực tiếp khi nhận hàng. <br>
    <br>
    <strong>1.10. Thông tin cá nhân và quyền riêng tư:</strong><br>
    <br>
    Ngoài hệ thống lưu trữ dữ liệu riêng, Rich Products Việt Nam có thể sử dụng một số dịch vụ của bên thứ ba để đảm bảo giao dịch (bên thứ ba cung cấp dịch vụ giao hàng, thanh toán, xuất hóa đơn,…). Thông tin của Quý khách hàng có thể được sử dụng theo chính sách của bên thứ ba cung cấp dịch vụ. <br>
    <br>
    Các thông tin này sẽ được thu thập, mã hóa và bảo mật theo chính sách của bên cung cấp dịch vụ. Các thông tin mà Rich Products Việt Nam thu thập và lưu trữ: <br>
    <br>
    - Họ tên, địa chỉ, số điện thoại, email, ngày sinh, giới tính và các thông tin khác được cung cấp trong phần đăng ký hoặc cập nhật thông tin tài khoản hoặc khi mua hàng. <br>
    - Nhận xét, đánh giá. <br>
    - Lịch sử tìm kiếm, mua hàng, thao tác người dùng trên Website của Rich Products Việt Nam. <br>
    - Các thông tin khi Quý khách hàng chủ động tham gia các chương trình do Rich Products Việt Nam tổ chức.
</div>
