<div class="top-header">
    <div class="mgn-top-header-left">
        <ul class="links-wrapper">
            <li class="link-item"><a href="{{store url=''}}about-us">{{trans "Về chúng tôi"}}</a></li>
            <li class="link-item"><a href="{{store url=''}}app-mobile">{{trans "Ứng dụng di động"}}</a></li>
            <li class="link-item"><a href="{{store url="#"}}">{{trans "Connect with us"}}</a></li>
        </ul>
        <div class="icon-wrapper">
            <div class="icon-wrapper-title">{{trans "Kết nối với chúng tôi"}}</div>
            <div class="list-socials">
                <a class="ig-icon" href="https://www.instagram.com/richproductsvietnam/"><span style="display: none;">Instagram</span></a>
                <a class="fb-icon" href="https://www.facebook.com/RichProductsVietnam"><span style="display: none;">Facebook</span></a>
                <a class="yt-icon" href="https://www.youtube.com/c/richproductsvietnam"><span style="display: none;">Youtube</span></a></div>
        </div>
    </div>
    <div class="mgn-top-header-right">{{block class="Magento\\Cms\\Block\\Block" block_id="region_popup_button"}}
        <div class="support-link"><a href="{{store url=''}}contact"><img src="{{media url="wysiwyg/cms/_12_2x.png"}}" alt="" />{{trans "Support"}}</a></div>
    </div>
</div>
