<!-- ---------------------------------------------------------------------- -->
<!-- NOTE: Please add the following <META> element to your page <HEAD>. -->
<!-- If necessary, please modify the charset parameter to specify the -->
<!-- character set of your HTML page. -->
<!-- ---------------------------------------------------------------------- -->
<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">
<!-- ---------------------------------------------------------------------- -->
<!-- NOTE: Please add the following <FORM> element to your page. -->
<!-- ---------------------------------------------------------------------- -->
<h1 class="b2me-form-title">{{trans "Let us know more about your needs"}}</h1>
<p class="b2me-form-des">{{trans "Please complete the form"}}</p>
<form action="https://test.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST">
    <input type=hidden name="oid" value="00D0k0000001QMf">
    <input type=hidden name="retURL" value="https://richs.izysync.com/b2me?success=1">
    <!-- ---------------------------------------------------------------------- -->
    <!-- NOTE: These fields are optional debugging elements. Please uncomment -->
    <!-- these lines if you wish to test in debug mode. -->
    <!-- <input type="hidden" name="debug" value=1> -->
    <!-- <input type="hidden" name="debugEmail" value="gjiang@rich.com"> -->
    <!-- ---------------------------------------------------------------------- -->
    <label for="first_name">{{trans "First Name"}}</label><input id="first_name" maxlength="40" name="first_name" size="20" type="text" /><br>
    <label for="last_name">{{trans "Last Name"}}</label><input id="last_name" maxlength="80" name="last_name" size="20" type="text" /><br>
    <label for="email">{{trans "Email"}}</label><input id="email" maxlength="80" name="email" size="20" type="text" /><br>
    <label for="company">{{trans "Company"}}</label><input id="company" maxlength="40" name="company" size="20" type="text" /><br>
    <label for="city">{{trans "City"}}</label><input id="city" maxlength="40" name="city" size="20" type="text" /><br>
    <label for="state">{{trans "State/Province"}}</label><input id="state" maxlength="20" name="state" size="20" type="text" /><br>
    <label for="title">{{trans "Title"}}</label><input id="title" maxlength="40" name="title" size="20" type="text" /><br>
    <label for="zalo">Zalo:</label><input id="zalo" maxlength="255" name="00N2v00000SXlno" size="20" type="text" /><br>
    <label for="facebook">Facebook:</label><input id="facebook" maxlength="255" name="00N0k000004THsn" size="20" type="text" /><br>
    <input type="submit" name="submit">
</form>
